### ISSUE TITLE
Reconcile preview view not working as expected

### ISSUE THREAD

**Issue by BobHarper1** [TechforgoodCAST/find-that-charity#5]
Just leaving this up as an issue that isn't working for me but might work for others, would be good to get feedback.

though `/reconcile` does define the preview window as per the [OpenRefine Preview API](https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API#preview-api), I can't get it to work (i.e. display the preview iframe on hover over a reconcile candidate) - though preview windows do work for other services (e.g. OpenCorporates).

```
{
	"name": "charitysearch",
	"identifierSpace": "http://rdf.freebase.com/ns/type.object.id",
	"schemaSpace": "http://rdf.freebase.com/ns/type.object.id",
	"view": {
		"url": "http://localhost:8080/charity/{{id}}"
	},
	"preview": {
		"url": "http://localhost:8080/preview/charity/{{id}}",
		"width": 430,
		"height": 300
	},
	"defaultTypes": [{
		"id": "/charity",
		"name": "charity"
	}]
}
```

and this preview itself also works fine outside of OpenRefine, e.g. http://localhost:8080/preview/charity/NIC100012

**Comment by drkane** [comment]
This has worked fine for me this morning - though you have to click on the reconcile candidate rather than hover. Might be worth checking the dev console in the openrefine page in case something is blocking the request?

**Comment by BobHarper1** [comment]
I don't think there was an actual problem - I had to clear and re-add the reconcile service. Now works as expected, with improved preview.
