### ISSUE TITLE
reconfiguring search definitions

### ISSUE THREAD

**Issue by BobHarper1** [TechforgoodCAST/find-that-charity#7]
@drkane if you check the branch at https://github.com/NICVA/find-that-charity/tree/es_query_yaml I've made a couple of changes that might make ongoing maintenance easier. Let me know if you like the look of it and I'll merge it into NICVA/master and submit a PR.

1. Reconfigured the ES search query json so that it is defined in it's own yaml file [`es_config.yaml`](https://github.com/NICVA/find-that-charity/blob/es_query_yaml/es_config.yml) which will be read in to the server command and converted to the json string. I find yaml easier to read and adapt than a json string, so good for ongoing development.
2. Added the CCEW, CCNI and OSCR charity number fields to the search query (see [these lines](https://github.com/NICVA/find-that-charity/blob/es_query_yaml/es_config.yml#L15-L20)). Means that a user can enter a known charity number in the search box and get a match.
3. Separated the ES search json for reconcile service, as it's likely that this will take different arguments than the web service version (e.g. names only). As with the above it's defined in its own yaml file [`recon_config.yml`](https://github.com/NICVA/find-that-charity/blob/es_query_yaml/recon_config.yml), and it's used in `/reconcile` `GET` and `POST` now instead of the previous search query.

**Comment by drkane** [comment]
Looks great - happy for a PR, you're right that YAML is a lot more readable that JSON for editing.
